# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup pyenv
        uses: "gabrielfalcao/pyenv-action@v7"
      - name: Setup pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependecies
        run: pipenv install -d # Install all dependencies, including development ones
      - name: Run test
        run: pipenv run pytest --log-cli-level DEBUG
